basePath: /
definitions:
  main.Message:
    properties:
      text:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: https://www.example.com/support
  description: This is the API for the Requestor Tools backend.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Requestor Tools API
  version: "1.0"
paths:
  /greet:
    get:
      description: Get a greeting message from the backend
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Message'
      summary: Greet the user
  /page/start:
    get:
      description: Renders a dynamic HTML start page.
      produces:
      - text/html
      responses:
        "200":
          description: HTML content of the start page
          schema:
            type: string
      summary: Start Page
schemes:
- http
swagger: "2.0"
